# Generated by Django 4.1.7 on 2023-06-06 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='ans',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='quesn',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='user_name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='quesn',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='user_name',
            new_name='username',
        ),
    ]
